# Generated by Django 5.2.4 on 2025-07-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_number', models.CharField(max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(help_text='E.g., Block A, Row 2, Opp. Gate', max_length=100)),
                ('category', models.CharField(choices=[('clothing', 'Clothing & Fashion'), ('foodstuff', 'Foodstuff'), ('electronics', 'Electronics'), ('building', 'Building Materials'), ('tools', 'Tools & Spare Parts'), ('cosmetics', 'Cosmetics & Beauty'), ('phones', 'Phones & Accessories'), ('others', 'Others')], max_length=50)),
                ('products', models.TextField(help_text='List of products or services sold')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
