# Generated by Django 5.2.4 on 2025-07-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='ad_banner',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_paid_ad',
            field=models.BooleanField(default=False),
        ),
    ]
