# Generated by Django 5.2.4 on 2025-07-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_ad_banner_shop_is_paid_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='paid_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
